//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shveya_praktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.ЗаказанныеИзделия = new HashSet<ЗаказанныеИзделия>();
        }
    
        public int Id { get; set; }
        public System.DateTime Дата { get; set; }
        public string Этап { get; set; }
        public int Заказчик { get; set; }
        public Nullable<int> Менеджер { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗаказанныеИзделия> ЗаказанныеИзделия { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Пользователи Пользователи1 { get; set; }
    }
}
