//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shveya_praktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Изделия
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Изделия()
        {
            this.ЗаказанныеИзделия = new HashSet<ЗаказанныеИзделия>();
        }
    
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public double Ширина { get; set; }
        public double Длина { get; set; }
        public int Количество { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗаказанныеИзделия> ЗаказанныеИзделия { get; set; }
    }
}
